syntax = "proto3";

package grpc.health.v1;

option go_package = "github.com/phrony-platform/runtime/gen/grpc/health/v1;grpc_health_v1";

message HealthCheckRequest {
  string service = 1;
}

message HealthCheckResponse {
  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
    SERVICE_UNKNOWN = 3; // Used only by the Watch method.
  }
  ServingStatus status = 1;
}

message HealthListRequest {}

message HealthListResponse {
  map<string, HealthCheckResponse.ServingStatus> statuses = 1;
}

service Health {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse);
  rpc List(HealthListRequest) returns (HealthListResponse);
  rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
}
